language: python

python:
  - "2.7"

services: mysql

#Django environment version
env:
  - DJANGO_VERSION=1.10.2 DJANGO_SETTINGS_MODULE="mysite.settings"

# command to install dependencies
install:
  - pip install -q -r requirements.txt

# setup MySQL database

before_script:
  - mysql -e 'create database pollsdb;'

# run tests
script: 
  - python manage.py test