language: python
  - "2.7"

#Django environment version
env:
  - DJANGO_VERSION=1.10.1

# command to install dependencies
install:
  - pip install --user --upgrade pip
  - pip install --user -r requirements.txt

# setup MySQL database
services:
  - mysql

before_script:
  - mysql -u root -e 'create database pollsdb;'

# run tests
script: "python manage.py test polls"