language: python
  - "2.7"

#Django environment version
env:
  - DJANGO_VERSION=1.10.1 DJANGO_SETTINGS_MODULE=mysite.settings

# command to install dependencies
install:
  - pip install -r requirements.txt

# setup MySQL database
services:
  - mysql

before_script:
  - mysql -e 'create database IF NOT EXISTS pollsdb;'

# run tests
script: 
  - python manage.py test -v 2