language: python
  - "2.7"

#Django environment version
env:
  - DJANGO_VERSION=1.10.1

# command to install dependencies
install:
  - pip install --user --upgrade pip
  - pip install --user -r requirements.txt

# run tests
script: "python manage.py test polls"