language: python
  - "2.7"

#Django environment version
env:
  - DJANGO_VERSION=1.10.2 DJANGO_SETTINGS_MODULE="mysite.settings"

# command to install dependencies
install:
  - pip install --user django==$DJANGO_VERSION --use-mirrors
  - pip install --user MySQL-python --use-mirrors
  - pip install --user mysqlclient --use-mirrors

# setup MySQL database
services:
  - mysql

before_script:
  - mysql -e 'create database IF NOT EXISTS pollsdb;'

# run tests
script: 
  - python manage.py test